# Generated by Django 6.0.3 on 2026-03-28 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_room_bans', to=settings.AUTH_USER_MODEL)),
                ('banned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bans', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='rooms.room')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'banned_user'], name='rooms_roomb_room_id_6a1e3f_idx'), models.Index(fields=['created_at'], name='rooms_roomb_created_6202d8_idx')],
                'constraints': [models.UniqueConstraint(fields=('room', 'banned_user'), name='unique_room_ban')],
            },
        ),
    ]
