# Generated by Django 6.0.3 on 2026-03-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_messageattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='dm_user1',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='direct_rooms_as_user1',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='room',
            name='dm_user2',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='direct_rooms_as_user2',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='room',
            name='is_direct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(
                condition=models.Q(is_direct=False) |
                (models.Q(dm_user1__isnull=False) & models.Q(dm_user2__isnull=False)),
                name='direct_room_requires_two_users',
            ),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(
                condition=models.Q(is_direct=False) |
                models.Q(dm_user1__lt=models.F('dm_user2')),
                name='direct_room_sorted_users',
            ),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(
                condition=models.Q(is_direct=True),
                fields=('dm_user1', 'dm_user2'),
                name='unique_direct_room_pair',
            ),
        ),
    ]
