# Generated by Django 6.0.3 on 2026-04-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_room_direct_dialog'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommembership',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
