# Generated by Django 6.0.3 on 2026-04-05 20:03

import rooms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_roommembership_last_read_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(upload_to='chat_attachments/', validators=[rooms.models.validate_attachment_upload]),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', '-created_at'], name='message_room_created_idx'),
        ),
    ]
