from django.urls import path
from .views import (
    RoomCreateView,
    PublicRoomListView,
    MyRoomListView,
    DirectDialogListView,
    DirectDialogCreateOrGetView,
    RoomDetailView,
    JoinRoomView,
    LeaveRoomView,
    RoomMessageListCreateView,
    MessageDetailView,
    ModerationDeleteMessageView,
    BanUserView,
    UnbanUserView,
    RemoveMemberView,
    RoomBansListView,
    MessageAttachmentUploadView,
    RoomMemberListView,
    UpdateMemberRoleView,
)

urlpatterns = [
    path('', PublicRoomListView.as_view(), name='public-rooms'),
    path('create/', RoomCreateView.as_view(), name='create-room'),
    path('my/', MyRoomListView.as_view(), name='my-rooms'),
    path('dialogs/', DirectDialogListView.as_view(), name='direct-dialogs'),
    path('dialogs/create-or-get/', DirectDialogCreateOrGetView.as_view(), name='direct-dialog-create-or-get'),
    path('<int:pk>/', RoomDetailView.as_view(), name='room-detail'),
    path('<int:pk>/join/', JoinRoomView.as_view(), name='join-room'),
    path('<int:pk>/leave/', LeaveRoomView.as_view(), name='leave-room'),
    path('<int:pk>/messages/', RoomMessageListCreateView.as_view(), name='room-messages'),
    path('<int:pk>/ban/<int:user_id>/', BanUserView.as_view(), name='ban-user'),
    path('<int:pk>/bans/<int:user_id>/', UnbanUserView.as_view(), name='unban-user'),
    path('<int:pk>/members/<int:user_id>/', RemoveMemberView.as_view(), name='remove-member'),
    path('<int:pk>/bans/', RoomBansListView.as_view(), name='room-bans'),
    path('<int:pk>/members/', RoomMemberListView.as_view(), name='room-members'),
    path('<int:pk>/members/<int:user_id>/role/', UpdateMemberRoleView.as_view(), name='update-member-role'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='message-detail'),
    path('room-messages/<int:pk>/moderation-delete/', ModerationDeleteMessageView.as_view(), name='moderation-delete-message'),
    path('room-messages/<int:message_id>/attachments/', MessageAttachmentUploadView.as_view(), name='message-attachment-upload'),
]