# Generated by Django 6.0.3 on 2026-03-28 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpresence',
            name='session_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userpresence',
            name='tab_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AddIndex(
            model_name='userpresence',
            index=models.Index(fields=['user', 'last_seen'], name='core_userpr_user_id_d0911a_idx'),
        ),
        migrations.AddIndex(
            model_name='userpresence',
            index=models.Index(fields=['last_seen'], name='core_userpr_last_se_2322a8_idx'),
        ),
        migrations.AddIndex(
            model_name='userpresence',
            index=models.Index(fields=['user', 'session_id', 'tab_id'], name='core_userpr_user_id_7e6d87_idx'),
        ),
        migrations.AddConstraint(
            model_name='userpresence',
            constraint=models.UniqueConstraint(fields=('user', 'session_id', 'tab_id'), name='unique_user_session_tab_presence'),
        ),
    ]
